[theme]
primaryColor="#808080" ##cor quando passa o mouse
backgroundColor="#FFFFFF" ##cor do fundo da página
secondaryBackgroundColor="#D3D3D3" ##cor lateral
textColor="#FF0000" ##cor do texto
font="sans serif" ##tipo da fonte
